version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  tomee:
    build: .
    container_name: tomee_container
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomee/webapps
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network
networks:
  app-network:
volumes:
  mysql-db-data:
